# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push to master or pull request
# events
on:
  push:
    branches: [master]
  pull_request:
    branches: ["*"]

env:
  EXTEND_ESLINT: true

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Get node version
      - name: Parse node version
        id: parse_node_version
        run: echo "::set-output name=version::$(cat .tool-versions | grep nodejs | cut -d' ' -f2)"

      # Install node. Also installs yarn
      - name: Setup node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ steps.parse_node_version.outputs.version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn packages
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install npm packages via yarn
        run: yarn install

      - name: Lint client
        run: yarn lint

      - name: Test client
        run: yarn test

      - name: Build client
        run: yarn build
        env:
          EXTEND_ESLINT: true

      # - name: e2e test client
      #   run: yarn test:e2e:ci
      #   env:
      #     CYPRESS_BASE_URL: http://localhost:5000
